### ISSUE TITLE
v0.14.0 , SPR-01 is discovered, but status Unavailable

### ISSUE THREAD

**Issue by MariusStensrod** [thomasloven/hass-plejd#90]
Upgraded to v0.14.0, deleted the old version of the integration and downloaded it again, as suggested in the release note. With this version, the SPR-01 is connected but not controllable "Unavailable": 
![bilde](https://github.com/user-attachments/assets/d1500292-999b-4b2c-92fb-a706fa6f4f1b)
I found this in the debug log, maybe connected to this issue?:
![bilde](https://github.com/user-attachments/assets/ef4a6197-236e-4b00-8e12-85d996e9a960)
![bilde](https://github.com/user-attachments/assets/76e38df9-5ce5-4d8f-8ee4-2f982b7f57db)

**Comment by thomasloven** [comment]
I think this should be fixed with 0.14.1

**Comment by t-n** [comment]
Still an issue for me in 0.14.1

`Traceback (most recent call last):
  File "/config/custom_components/plejd/plejd_site.py", line 176, in _ping
    if not await self.manager.ping():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplejd/__init__.py", line 114, in ping
    retval = await self.mesh.ping()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplejd/ble/__init__.py", line 180, in ping
    if not await self.connect():
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplejd/ble/__init__.py", line 167, in connect
    self._publish(self._connect_listeners, {"connected": True})
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplejd/ble/__init__.py", line 69, in _publish
    listener(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplejd/__init__.py", line 102, in _update_connected
    d.update_state(available=state["connected"])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplejd/interface/plejd_device.py", line 73, in update_state
    state = self.parse_state(state, self._state)
TypeError: PlejdRelay.parse_state() takes 2 positional arguments but 3 were given`

**Comment by MariusStensrod** [comment]
Still Unavailable. Instead of one error message in the log,  i now got two. 
![bilde](https://github.com/user-attachments/assets/288158aa-f156-4d6d-9c39-96be7d54921f)
![bilde](https://github.com/user-attachments/assets/488c1fd0-fe55-413a-8774-12c17581251d)

**Comment by thomasloven** [comment]
I guess I failed in pushing the changes.
Try 0.14.2

**Comment by thomasloven** [comment]
Thanks for the quick feedback!
